---
#Main installation actions
#https://clickhouse.com/docs/en/getting-started/#installation

- name: Install by YUM | Ensure yum-utils package installed
  yum:
    name: "yum-utils"
    state: present
  become: true
  tags: [install]

- name: Install by YUM | Ensure clickhouse repo installed
  command: "yum-config-manager --add-repo {{ clickhouse_repo }}"
  tags: [install]
  become: true

- name: Install by YUM | Ensure clickhouse package installed (latest)
  yum:
    name: "{{ clickhouse_package }} "
    state: "{{ clickhouse_version }}"
  become: true
  tags: [install]
  when: clickhouse_version == 'latest'

- name: Install by YUM | Ensure clickhouse package installed (version {{ clickhouse_version }})
  yum:
    name: "{{ clickhouse_package | map('regex_replace', '$', '-' + clickhouse_version) | list }}"
    state: present
    disable_gpg_check: "{{ true if clickhouse_version == '19.4.0' else omit }}" 
  become: true
  tags: [install]
  when: clickhouse_version != 'latest'
